#baseurl: 
baseurl: /examples
exclude: ['README.md', 'node_modules', 'gulpfile.js', 'package.json', 'assets/css/*.scss']

exchange1:
- {
    id: 'exchange1-01',
    number1: '250',
    currency1: 'руб',
    number2: '160 000',
    currency2: 'fun'
}
- {
    id: 'exchange1-02',
    number1: '500',
    currency1: 'руб',
    number2: '320 000',
    currency2: 'fun',
    number3: '+ 30 000',
    currency3: 'fun'
}
- {
    id: 'exchange1-03',
    number1: '1 000',
    currency1: 'руб',
    number2: '640 000',
    currency2: 'fun',
    number3: '+ 60 000',
    currency3: 'fun'
}
- {
    id: 'exchange1-04',
    number1: '5 000',
    currency1: 'руб',
    number2: '1 220 000',
    currency2: 'fun',
    number3: '+ 120 000',
    currency3: 'fun'
}
- {
    id: 'exchange1-05',
    number1: '10 000',
    currency1: 'руб',
    number2: '2 540 000',
    currency2: 'fun',
    number3: '+ 120 000',
    currency3: 'fun'
}
- {
    id: 'exchange1-06',
    number1: '20 000',
    currency1: 'руб',
    number2: '2 890 000',
    currency2: 'fun',
    number3: '+ 60 000',
    currency3: 'fun'
}

exchange2:
- {id: 'exchange2-01', number1: '100', currency1: 'баллов', number2: '10', currency2: 'руб'}
- {id: 'exchange2-02', number1: '800', currency1: 'баллов', number2: '100', currency2: 'руб'}
- {id: 'exchange2-03', number1: '3 000', currency1: 'баллов', number2: '500', currency2: 'руб'}
- {id: 'exchange2-04', number1: '8 000', currency1: 'баллов', number2: '2 000', currency2: 'руб'}
- {id: 'exchange2-05', number1: '16 000', currency1: 'баллов', number2: '8 000', currency2: 'руб'}
- {id: 'exchange2-06', number1: '30 000', currency1: 'баллов', number2: '30 000', currency2: 'руб'}
